// src/constants/MessageConstants.ts
export const MessageConstants = {
  USER_REGISTER_SUCCESS: "User registered successfully.",
  LOGIN_SUCCESS: "Login successful.",
  GOOGLE_SIGNIN_SUCCESS: "Google Sign-In successful.",
  INTERNAL_SERVER_ERROR: "An internal server error occurred. Please try again later.",
  GOOGLE_SIGNIN_FAILED: "Google Sign-In failed. Please try again.",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required.",
  INVALID_REFRESH_TOKEN: "Invalid refresh token. Please login again.",
  ID_TOKEN_REQUIRED: "ID token is required.",
  LOGIN_FAILED: "Login failed. Please check your credentials.",
  USER_ID_NOT_FOUND: "User ID not found in the request data.",
  USER_NOT_FOUND: "User not found.",
  PROFILE_FETCHED_SUCCESS: "User profile fetched successfully.",
  EMAIL_REQUIRED: "Email is required.",
  PASSWORD_RESET_SUCCESS: "Password reset successful.",
  FILE_NOT_UPLOADED: "No file uploaded.",
  LOGOUT_SUCCESS: "Logged out successfully.",
  USER_ALREADY_EXISTS: "User with this email already exists",
  ACCESS_TOKEN_REFRESHED: "Access token refreshed successfully",
  RESTAURENT_STATUS_UPDATED: "Restaurent status updated successfully.",
  RESTAURENT_BLOCKED: "Restaurent blocked successfully.",
  RESTAURENT_UNBLOCKED: "Restaurent unblocked successfully.",
  USER_BLOCKED: "User blocked successfully.",
  USER_UNBLOCKED: "User unblocked successfully.",
  REFRESH_TOKEN_FAILED: "Failed to refresh tokens.",
  ACCESS_DENIED: "Access denied.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  PROFILE_UPDATED_SUCCESS: "Profile updated successfully",
  EMAIL_ALREADY_EXISTS: "Email already in use",
  OTP_SENT: "OTP sent successfully",
  INVALID_OTP: "Invalid OTP",
  OTP_SENT_FAILED:'OTP SENT FAILED',
  INVALID_PASSWORD: "Wrong Password.",
  RESTAURENT_APPROVAL_REQUIRED: "Your account requires administrator approval to perform this action",
  REQUIRED_FIELDS_MISSING: "All required fields must be provided",
  PROFILE_PICTURE_UPLOADED: "Profile picture uploaded successfully",
  UNAUTHORIZED: "Unauthorized access. Please log in.",
  BOOKING_CREATED: "Booking created successfully.",
  BOOKINGS_FETCHED: "Bookings fetched successfully.",
  BOOKING_NOT_FOUND: "Booking not found.",
  BOOKING_CANCELLED: "Booking cancelled successfully.",
  RESTAURANT_NOT_FOUND: "Restaurant not found", // Added for clarity
  RESTAURENT_PENDING_APPROVAL: "Restaurant is pending approval",
  // New constants for Branch operations
  BRANCH_CREATED: "Branch created successfully",
  BRANCH_ALREADY_EXISTS: "Branch with this email already exists",
  BRANCH_NOT_FOUND: "Branch not found",
  BRANCHES_FETCHED: "Branches fetched successfully",
  BRANCH_UPDATED: "Branch updated successfully",
  BRANCH_DELETED: "Branch deleted successfully",
  PARENT_RESTAURANT_REQUIRED: "Parent restaurant ID is required",
  IMAGE_UPLOAD_FAILED: "Failed to upload branch image",
  PASSWORD_HASHING_FAILED: "Failed to hash password",
  PENDING_APPROVAL: "Your account is pending approval.",
  // New constants for Coupon operations
  COUPON_CREATED: "Coupon created successfully",
  COUPON_ALREADY_EXISTS: "Coupon with this code already exists",
  COUPON_NOT_FOUND: "Coupon not found",
  COUPONS_FETCHED: "Coupons retrieved successfully",
  COUPON_UPDATED: "Coupon updated successfully",
  COUPON_DELETED: "Coupon deleted successfully",
  RESERVATION_CREATED: "Reservation created successfully",
  RESERVATION_NOT_FOUND: "Reservation not found",
  RESERVATIONS_FETCHED: "Reservations fetched successfully",
  RESERVATION_CANCELLED: "Reservation cancelled successfully",
  RESERVATION_CONFIRMED: "Reservation confirmed successfully",
  RESERVATION_PAYMENT_FAILED: "Reservation marked as payment failed",
  AVAILABLE_TABLES_FETCHED: "Available tables fetched successfully",
  PAYMENT_ORDER_CREATED: "Payment order created successfully",
  RESERVATION_ALREADY_CANCELLED: "Reservation is already cancelled",
  INVALID_RESERVATION_STATUS: "Invalid reservation status for this operation",
  NO_AVAILABLE_TABLES: "No available tables for selected time slot",
  INVALID_BRANCH_OR_TABLE: "Invalid branch or table type",
  PARTY_SIZE_EXCEEDED: "Party size exceeds table capacity",
  INVALID_COUPON: "Invalid or expired coupon",
  MIN_ORDER_AMOUNT_REQUIRED: "Minimum order amount not met for coupon",
  PERMISSION_DENIED: "You do not have permission to perform this action",
  WALLET_CONFIRMATION_FAILED: "Failed to confirm reservation with wallet",
  RESERVATION_CONFIRMED_WITH_WALLET: "Reservation confirmed with wallet",
  // New constants for TableType operations
  TABLE_TYPE_CREATED: "Table type created successfully",
  TABLE_TYPE_NOT_FOUND: "Table type not found",
  TABLE_TYPES_FETCHED: "Table types fetched successfully",
  TABLE_TYPE_UPDATED: "Table type quantity updated successfully",
  TABLE_TYPE_DELETED: "Table type deleted successfully",
  // New constants for Wallet operations
  WALLET_DATA_FETCHED: "Wallet data fetched successfully",
  WALLET_ORDER_CREATED: "Wallet order created successfully",
  WALLET_MONEY_ADDED: "Money added to wallet successfully",
  INVALID_AMOUNT: "Amount must be a positive number",
  INSUFFICIENT_BALANCE: "Insufficient wallet balance",
};